general:
  region: 'HNC'                        # ['HNC', 'LUNG']
  seed: 42                             # random seed
  firstRun: false                      # if this is the first run of this experiment (# if True, makes new experiment folder)
  experiment_name: 'Model_reproductions'   # name of the experiment folder (contains all trial folders)
  trialNumber: "Multi_tox"               # name of the trial folder (contains fold folders)
  resultsCurrentDirectory: ""          # current working directory
  testMode: False                      # if testing the code (e.g. less patients, or less epochs, etc.)
  use_test_set: False                  # if the test dataset should be loaded
  dataset_amounts_experiment: False    # whether the dataset_amounts_experiment is being performed using bootstrapping

columns:
  labels: ['Aspiration_M06', 'Dysphagia_M06', 'Sticky_M06', 'Taste_M06', 'Xerostomia_M06']           # the endpoints the model is (going to be) trained on (list)
  labels_types: ["Binary", "Binary", "Binary", "Binary", "Binary"]
  clinical_features: 
  - Geslacht
  - Leeftijd
  - Aspiration_W01_Helemaal_niet
  - Aspiration_W01_Een_beetje
  - Aspiration_W01_Nogal_Heel_erg
  - Dysphagia_W01_Grade0_1
  - Dysphagia_W01_Grade2
  - Dysphagia_W01_Grade3_4
  - Sticky_W01_Helemaal_niet
  - Sticky_W01_Een_beetje
  - Sticky_W01_Nogal_Heel_erg
  - Taste_W01_Helemaal_niet
  - Taste_W01_Een_beetje
  - Taste_W01_Nogal_Heel_erg
  - Xerostomia_W01_Helemaal_niet
  - Xerostomia_W01_Een_beetje
  - Xerostomia_W01_Nogal_Heel_erg

paths:
  csv: "/home/macraedc/data/MICCAI"  # directory to folder containing the dataset csv
  #images: "/home/macraedc/data/dataset_full_renamed"             # directory to the folder containing the patient images (numpy files)
  images: "/home/macraedc/data/dataset_full_2mm_anonymized"
  results: "/home/macraedc/results/MICCAI" # directory for where you want to save the results

model:
  model_name: "TransRP"            # model architecture ['cnn', 'resnet', 'densenet', 'ViT', 'TransRP', etc.]
  output_head:
    name: "multilabel"        # output module name (i.e. linear layers type)   ['multilabel', ]
    # Linear layer params (output head)
    n_linear_layers: 1                        # number of (shared) linear layers
    linear_units: [256]                        # size of each (shared) linear layers
    n_clinical_layers:                   # number of clinical feature layers
    clinical_variables_linear_units: []  # sizes of each clinical feature layers
    clinical_variables_position: 1            # index of `linear_units` to which the clinical features are concatenated (1 = first linear_unit). If there are no linear layers, the clinical features are concatenated to the flattening layer
    n_linear_layers_endpoint: 2               # number of non-shared linear layers for all endpoints
    linear_units_endpoint: [16]               # size of each non-shared linear layer
    num_ohe_classes: 1                        # number of output logits per endpoint [1, 2] (usually 1!)
  densenet:  
    model_depth: 121  # DenseNet model size [121, 169, 201, 264]
  TransRP:
    image_encoder: 'densenet'  # which model to use an an image encoder ['resnet', 'densenet'] (requires their respective configs)
    clinical_features_method: 'm2'  # which method to use to insert features into (or after) the ViT ["m1", "m2", "m3", "mcb"] 
    cls_hidden_dim: 128   # the sizes of the linear layers used to embed the clinical features into a CLS token
    cls_gating: False              # whether to use the cls gating mechanism to weigh the clinical features
    cls_merge_image_features: False # i the output of the ViT should be the CLS token and the mean of the image tokens (if false, only the CLS token is used)
    cls_per_class_weighting: False  # aply an alpha per class to the CLS token
    vit_patch_size: [1,1,1]       # size of the feature map patches
    vit_dim: 256                  
    vit_depth: 4            
    vit_heads: 64
    vit_mlp_dim: 1024
    vit_dropout_p: 0
  
    
  # general model params
  lrelu_alpha: 0.1                    # leaky ReLu value for the convolutional layers
  dropout_p: 0.02595495832717444      # dropout probability 
  use_bias: True                      # whether or not to use a bias term in the conv. layers
  

data:
  source: 'PRIMA'                                     # the source of the dataset you are using (change this for external validation, see constants.py) # ['PRIMA', 'UMCG', 'MDACC']
  dataset_csv: 'MICCAI_NTCP_cohort.csv'                         # name of the csv containing the IDs, clinical features, and endpoints
  stratify_on: []                                    # which column names to use in stratified sampling (list of strings)
  excluded_variable_name: [] # ExcludedVar           # column name of variable to exlude patients by
  excluded_values: [] # ExcludedValue                # values of ^this^  variable to exclude patients by
  image_keys:  ['ct', 'rtdose', 'segmentation_map']  # the keys of the images to load
  image_num_dimensions: 3                            # dimension of each image (each image is 3D, so this is = 3)
  n_training_patients_list: []                       # list of number of patients to use for training (only used if 'dataset_amounts_experiment'=True)
  event_endpoint_time_unit: "months"  # time unit for the event endpoints (e.g. "days", "months", "years"), should match the time unit in the dataset column names

  dataloader:
    dataset_type: 'cache'              # ['standard', 'cache', 'smartcache'] # cache: loads all data into RAM for faster training, smartcache: loads a fraction of data into memory
    num_workers: 8                     # number of workers (cores) to use for data loading in each training batch
    smartcache:
      cache_rate: 0.5                  # what fraction of the dataset should be kept in the RAM 
      num_replace_workers: 4           # number of workers to replace cache with

  preprocessing:
    isEnabled: true                   # whether or not preprocessing steps should be applied to the image data files
    crop: true                         # if the image files need cropping
    crop_shape: [96, 96, 96]           # dimension to crop to
    needs_scaling: ["ct", "rtdose", 'pet'] # , 'mri']         # list of image types that need to be scaled (a_min, a_max, b_min, b_max, and clip must be defined)
    needs_label_mapping: ["segmentation_map", "gtv_total"]   # list of image types that need label mapping (i.e. binarising OAR structures. target_labels must be defined)
    ct: 
      a_min: -200            # lowest range to clip from
      a_max: 400             # highest range to clip from
      b_min: 0               # lowest range to clip to
      b_max: 1               # higher range to clip to
      clip: true             # whether or not to clip using the above-mentioned clipping ranges
      cmap: 'gray'           # colormap to use when plotting CT images  
      legend_title: 'HU'       # title for the colorbar when plotting CT images
    rtdose:
      a_min: 0
      a_max: 8000
      b_min: 0
      b_max: 1
      clip: true
      #cmap: 'gray'          
      legend_title: 'cGy'       
    mri:              # example of how to scale an MRI image
      a_min: 0
      a_max: 12345
      b_min: 0
      b_max: 1
      clip: true
    pet:             # example of how to scale a PET image
      a_min: 0
      a_max: 20      # SUV units
      b_min: 0
      b_max: 1
      clip: true
      cmap: 'hot'
      legend_title: 'SUV'
    mandible_dose:              # example of how to scale an MRI image
      a_min: 0
      a_max: 8000
      b_min: 0
      b_max: 1
      clip: true
    segmentation_map:      # value encoding of the structures in `segmentation_map.npy`, before feeding to model (set to 0 if don't want to include that structure)
      target_labels: [0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.1, 0.1, 0.0, 0.0, 0.0, 0.0]
      outline_color: 'deeppink'  # color to use for outlining the segmentation maps, when plotted over images (e.g. CT)
      normalised_cmap: 'gray'  # colourmap to use for normalised model inputs (this is always used when the max value is >=1)
      linewidth: 2
      alpha: 0.8
      # cmap can be either a matplotlib colormap name (string) or a list of color names (the latter of which is handy when you only want to plot certain structures distinctly):
      # empty cmap colour names ('') will be transparent when plotting
      cmap: 'nipy_spectral' # ['black', '', 'pink', 'tab:red', 'tab:purple', 'tab:brown', 'tab:pink', 'gold', 'tab:olive', 'tab:cyan', 'gold', 'deepskyblue', 'crimson', 'lime', 'navy', 'magenta', 'darkorange', 'darkviolet', 'cyan'] # 'turbo'
    gtv_total:
      target_labels: [0.0, 1.0]  # target labels for the GTV total segmentation map (0 = no GTV, 1 = GTV present)
      outline_color: 'red'
      linewidth: 2
      alpha: 0.8
      cmap: 'PuRd'
  kFolds:
    n_splits: 5           # the number of data splits to make
    n_iterations: 5       # the number of k-fold iterations to perform (i.e. how many to actually train, must be less than or equal to 'n_splits')
    validation_size: 0.2  # if only 1 split; this is the size of the validation set, the rest goes to training set
    split_strategy: 'stratified'  # how to perform the splitting of K_folds ['stratified', 'random']
    

  equalizer:
    isEnabled: false     # whether or not to over/under-sampling the training dataset
    ratio: 0.5           # over/under sample until the ratio of positive and negative instances of each class reaches this value
    resamplingDirection: 'over'   # ['over', 'under']  

  augmentation:
    isEnabled: true      # whether or not to apply random augmention during training
    prob: 0.5            # probability of applying each augmentation (flip is always 0.5)
    list:
      flip:
        isEnabled: True  # left-right flipping (w. 50% chance)
      random_crop:       
        isEnabled: True  # randomly crop the image (uses the crop_shape defined in preprocessing)
      affine:
        isEnabled: True    # perform affine transformations
        scale_max: 0.02
        translate_max: 6
        z_scale: -0.2
      rotate:
        isEnabled: True    # random rotation
        max: 15            # max degrees to rotate by
      noise:
        isEnabled: True    # add random noise
        mean: 0            # mean of random noise to add to the image
        std: 0.01           # standard deviation of that nose
        
    mixup:
      isEnabled: False     # whether to apply MixUp augmention during training
      alpha: 1.7244367682922501        # alpha value for MixUp

training:
  max_epochs: 200            # max number of epoch to train for
  batch_size: 8              # training batch_size
  validation_interval: 1     # validate after X training epochs
  stopping_criteria: "loss"  # What criteria to use for early stopping ['loss', 'metric']
  patience: 10               # early stopping patience
  show_progress_bar: True    # whether to show the progress bar on each training epoch (recommend=False for Habrok)

  optimizer:
    name: "Adam"             # which optimiser to use ['Adan', 'AdamW', 'SGD', 'RMSProp']
    learning_rate: 0.0001     # starting learning rate during training
    weight_decay: 0.0        # optimiser weight decary
    momentum: 0.8            # optimser momentum (for 'SGD')

  loss:
    name: "BCE"    # loss function ['BCE', 'focal', 'hill', 'ASL', 'NLLL']
    reduction: "none"  # loss function reduction (keep as 'none' !!!)
    BCE:
      pos_weight: [1]    # weights for positive instances of each class (list of same length as endpoint labels list) (default:[1])
    focal:
      gamma: 2          # gamma for focal loss (default: 2)
      alpha: 0.25       # alpha value for focal loss (default: 0.25)
    ASL:
      gamma_neg: 4     # gamma_negative value for focal loss (default: 4)
      gamma_pos: 1     # gamma_positive value for focal loss (default: 1)
    
  scheduler:
    name: False         # Name of scheduler to use [None, "cosine", "step", "plateau"]
    cosine:
      T_0: 40             # (cosine) number of epochs until  restart
      T_mult: 1           # (cosine) a factor increases after a restart (default: 1)
      eta_min: 0.00000001 # (cosine)  Minimum learning rate. Default: 0.
    step:
      step_size: 50       # (step) number of epochs between each learning rate decay
      gamma: 0.1          # (step) learning rate decay factor
    plateau:
      mode: 'min'               # 'min' or 'max' depending on whether the monitored metric needs to be minimised or maximised
      factor: 0.1               # factor to reduce the learning rate by
      patience: 10              # number of epochs with no improvement after which learning rate will be reduced
      min_lr: 0.00000001        # minimum learning rate

  GradNorm:                  
    isEnabled: False         # whether to use GradNorm to balance the gradients of the labels' losses
    alpha: 0.5               # alpha value for GradNorm (higher -> more imbalance. 0=equal. recommended: less than 2)
    learning_rate: 0.001     # learning rate for the GradNorm optimiser

evaluation:
  main_metric: 
    Binary: "AUC"    # the metric shown during training
    Event: "C-index"
  metrics_list: ["AUC"] #  ["AUC", "accuracy"]   # the metrics to calculate at the end of each fold (list of strings, see constant.py for options)
  metrics:
    threshold: 'YoudenJ'  # how to define the classification metrics threshold
    calibration_bins: 10  # number of bins to use in the calibration metrics
  visualisations: 
    list: ['calibration', 'reliability', 'confusion_matrix', 'roc_curve', 'kaplan_meier'] # which plots to save per fold
    n_bins: 10            # nunber of bins to use in the calibration and reliability plot
    kaplan_meier_max_timepoint: 60  # maximum time point to show in the Kaplan-Meier plot



uncertainty:
  seed: 42                        # random seed for uncertainty estimation
  method: 'DeepEnsemble'          # method to use for uncertainty estimation ['MC_dropout', 'DeepEnsemble', 'TTA']  
  metric: 12345
  deep_ensemble:
    n_models: 10
  MC_dropout:
    n_forward_passes: 50          # number of forward passes to perform for each model in the ensemble
    dropout_p: 0.2 
  TTA:
    n_forward_passes: 50
  dataset_split:
    n_splits: 5                   # the number of data splits to make
    validation_size: 0.2          # if only 1 split; this is the size of the validation set, the rest goes to training set
    split_strategy: 'stratified'  # how to perform the splitting of K_folds ['stratified', 'random']
    




hyperparam_tuning:
  WandB:
    isEnabled: false                   # whether or not to log to Weights & Biases
    API_Key: "c7f0f65fac8b7178ad7c5859ba6114775b16e694"     # WandB API key of your account
  optuna:
    isEnabled: False                    # perform hyperparameter tuning
    objectives: ["val_mean_AUC"]       # which metrics to optimise on (can be multi-objective)
    objective_direction: ["maximize"]  # direction to optimise each metric in. must be the same length (and order) as objectives
    n_trials: 100                      # number of trials to perform
    n_startup_trials: 30               # number of random trials to perform at the start of the optuna experiment
    kill_trial_threshold: 0.6          # kill a trial (after 3 folds) if the mean metric value is below this threshold
    set_new_seeds: True                # whether to set new seeds for each trial
  # ----  Custom Params -------
  # Location:= path of the variable in the config
  # hyperparams:
  #   Weight_decay: 
  #     name: 'Weight_Decay'
  #     type: 'float'
  #     location: ["training",'optimizer','weight_decay']
  #     min: 0
  #     max: 1




saving:
  config: True               # whether to save the config as a .yaml fule
  best_model: True           # whether to save the model weights on each fold
  plot_training_slices:      # plotting the model inputs on certain batches
    isEnabled: True          # enable/disable these plots
    folder_name: 'figures'   # folder name to save the .png files into
    every_n_epochs: 50       # make a plot of the first batch every N epochs
    n_patients_per_epoch: 1  # how many patients to plot from a batch
    n_slices_per_patient: 8  # how many slices to plot per patient
    layer_plotting_order: ["CT", "PET", "RTDOSE", "mandible_dose", "RTSTRUCT", "segmentation_map", "GTV", "Attention"] # the order in which to plot the layers
    colormap_layers: ["Attention", "RTDOSE", "PET", "CT", "GTV", "RTSTRUCT", "segmentation_map", "mandible_dose"] # priority list for colourmaps per row (first is most important)
  
  filenames:
    model_summary: "model_summary.txt"    # filename of the model summary
    config_yaml: "DlModel_Config.yaml"    # filename of the config to save
    model_weights: "DlModel_Weights.pth"  # filename of the (best) model weights
    library_dependencies_file: "library_dependencies.txt"
    predictions_csv: "model_predictions.csv"  # filename of the predictions on the train/val sets
    test_set_predictions_csv: "test_set_predictions.csv"   # filename of the predictions in the test set (external validation set source are appended to this, e.g. "_MDACC.csv")
    ensemble_predictions_csv: "ensemble_predictions.csv"   # filename of the ensemble predictions
      
  ModelCard:
    isEnabled: True
    saveLocation : 'C:/Users/WalR/OneDrive - UMCG/Documents/Modelcards/'
    loaded_projectcard_filename : 'projectdetails_card'
    saved_modelcard_filename : 'autogenerated_card'

