general:
  seed: 42
  device: "cuda"
  trialNumber: "Trial_?"
  patientGroup: 0
  resultsCurrentDirectory: ""

columns:
  label: ["RP_OneYear"]
  clinical_features: ["SmokerActive","SmokerStopped", "Gender",
  "Age","ChemoRad", "SequantialChemo", "ImmunoTherapy",
  "OperationPerformed", "T_Stage","N_Stage","M_Stage"]
  #DosePerFraction","FractionAmount","RT_TreatmentDuration", "Tumour_UpperLoc","Tumor_MiddleLoc","Tumor_LowerLoc"
  logistic_regression_features: ['']

paths:
  csv: "Z:/Robert/DataImports/Data_23_07_2024/ClinicalData/2024_08_27/"
  images: "Z:/Robert/DataImports/Data_23_07_2024/ImageData/"
  output: "C:/Users/r.van.der.wal/Documents/Detox_lung/Results/"
  results: "C:/Users/r.van.der.wal/Documents/Detox_lung/Results/"

data:
  trainfile: 'stratified_sampling_full_manual_94.csv'
  valfile: 'stratified_sampling_full_manual_94.csv'
  splitvar: ""
  patientVar: 'PatientID'
  stratifyList: ["RP_OneYear","SmokerActive","ImmunoTherapy"]
  Excluded: "ExcludeVar"

  kFolds:
    isEnabled: True
    Iterations: 3
    Splits: 5

  equalizer:
    isEnabled: True
    ratio: 0.5
    resamplingDirection: 'up'

  augmentation:
    isEnabled: true
    augmentation_list: ['flip','affine','rotate']
    prob: 0.5
    strength: 1

model:
  model_name: "dcnn_pooling"
  num_classes: 1
  num_down_blocks: 5
  filters: [8, 8, 16, 16, 32]
  kernel_sizes: [7, 5, 4, 3, 3]
  strides: [[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
  pad_value: 0
  lrelu_alpha: 0.1
  dropout_p: 0.06087816611628816
  perform_pooling: False
  linear_units: [16]
  clinical_variables_position: 1
  clinical_variables_linear_units: []
  clinical_variables_dropout_p: [0.3581947628028867]
  use_bias: True
  pooling: 'max'
  pooling_size: 2
  normalization: 'batch'
  conv_block_layers: 1
  num_ohe_classes: 1
  linear_units_endpoint: [64]

preprocessing:
  isEnabled: false
  crop: false
  crop_shape: [96, 96, 96]
  ct:
    a_min: -1200
    a_max: 400
    b_min: 0
    b_max: 1
    clip: true
  rtdose:
    a_min: 0
    a_max: 8000
    b_min: 0
    b_max: 1
    clip: true
  segmentation_map:
    target_labels: []

training:
  max_epochs: 50
  batch_size: 8
  validation_interval: 1
  patience: 16
  optimizer:
    name: "Adam"
    learning_rate: 0.0001
    weight_decay: 0.05
  loss:
    name: "multi-loss"
    weight: [1]
    reduction: "mean"
  scheduler:
    name: "cosine"
    T_0: 40
    T_mult: 1
    eta_min: 0.00000001
  validation:
    num_auc_batches: 1

visualizations:
  calibration:
    num_bins: 10

hyperparam_tuning:
  ProjectName: 'DETOX-Lung_Project_9'
  WandB:
    IsEnabled: true
    MetricsMonitor: [ "train_AUC","train_loss","train_acc",
      "eval_AUC","eval_loss","eval_acc"]
  optuna:
    IsEnabled: True
    studyName: "DETOX-Lung_Project_9"
    n_trials: 5
    storagePath: "Unknown"
  # ----  Custom Params -------
  # Location:= path variabele in config
  hyperparams:
    #patience:
    #  type: 'int'
    #  location: ['training','patience']
    #  min: 2
    #  max: 10
    learning_rate: 
      name: 'Learning_rate'
      type: 'float'
      location: ['training','optimizer','learning_rate']
      min: 0.0004
      max: 0.001
    optimizer:
      name: "Optimizer" 
      type: 'categorical'
      location: ["training",'optimizer','name']
      options: ['AdaBound']
    
    #leaky_relu_alpa:
    #  type: 'float'
    #  location: ['training','optimizer','learning_rate']
    #  min: 0.03
    #  max: 0.1
    batch_size:
      name: batch_size
      type: 'int'
      location: ["training","batch_size"]
      min: 6
      max: 16
      step: 2

    augmentation_strength:
      name: augmentation_strength
      type: 'float'
      location: ['data','augmentation',"strength"]
      min: 0.2
      max: 3

    augmentation_probability:
      name: augmentation_probability
      type: 'float'
      location: ['data','augmentation',"prob"]
      min: 0.2
      max: 0.8

    #n_down_blocks:
    #  type: 'int'
    #  name: 'n_down_blocks'
    #  location: ['model','num_down_blocks']
    # min: 1
    #  max: 6
    #  step: 1
    #  log: False
  
  # Complex hyperparams
  derived:
    n_down_blocks:
      filters:
        type: 'int'
        name: 'filter'
        location: ['model','filters']
        min: 8
        max: 64
        step: 8
        log: False
      kernel_sizes:
        type: 'int'
        name: 'kernel_size'
        location: ['model','kernel_sizes']
        min: 3
        max: 5
        step: 2
        log: False
      strides:      
        type: 'categorical'
        name: 'stride'
        location: ['model','strides']
        options: [[1,1,1]]

    #leaky_relu_alpa:
    #  type: 'float'
    #  location : [][],
    # min : 0.03
    #  max : 0.1
    #equalizer_ratio: 
    #  type: 'float'
    #  location: ['data',"equalizer",'ratio']
    #  min : 0.2 
    #  max : 0.5
        
Save:
  config: True
  output_values: True
  best_model: False
  fileNames:
    modelSummary: "modelSummary.txt"
      