model_name = "resnet_dcnn_lrelu"

# model parameters

seg_target_labels = [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
features_dl = ['Age']
endpoint_list = ["Taste_M06"]

n_input_channels = 3 
conv_block_layers = 1 
filters = [16, 16, 32, 64]
kernel_sizes = [[1,5,5], [1,4,4], [1,3,3], [1,3,3]]
strides = [[2,2,2], [2,2,2], [2,2,2], [2,2,2], [1,1,1]]  
normalization = "instance"
pad_value = 0  # (Padding) Value used for padding.
lrelu_alpha = 0.1  # (LeakyReLU) Negative slope.
pooling_conv_filters = "NONE"  
perform_pooling = false
pooling = "NONE" 
pooling_size = 2 
# linear layers
clinical_variables_position = 1
clinical_variables_linear_units = [32] 
linear_units = [32] 
dropout_p = 0.05
linear_units_endpoint = []
use_bias = true



# training parameters
weight_init_name = 'kaiming_uniform' 
kaiming_mode = 'fan_in' 
kaiming_nonlinearity = 'leaky_relu' 
gain = 0
optimizer_name = 'ada_belief'
momentum = 0.2
weight_decay = 0.03
hessian_power = 1.0
use_lookahead = false
lookahead_k = 5
lookahead_alpha = 0.5 


loss_function_name = 'bce'   
label_weights = false 
label_pos_weights = false 

auxiliary_loss_func_name = "NONE" ## "SB-ECE" | "ESD" | None
SB_ECE_n_bins = 15
SB_ECE_temperature = 0.005
loss_reduction = 'none' # Daniel: do not change this
label_smoothing = 0  
scheduler_name = "NONE" # 'cosine' # [None, 'cosine', 'cyclic', 'exponential']. 
grad_max_norm = 1 
lr = 0.0005  
T_0restart = 40 
T_mult = 1 
eta_min = 1e-10 

batch_size = 2

# augmentation parameters

perform_data_aug = true
data_aug_p = 0.1
data_aug_strength = 0.2
# AugMix
perform_augmix = true
mixture_width = 3  
mixture_depth = [1, 3] 
augmix_strength = 3
# MixUp
perform_mixup = false
mixup_alpha = 1.5



submodels_features_list = [
    [
        ['Parotid_meandose', 'OralCavity_Ext_meandose', 'Age'], # Taste (no submodels)
    ]
    ]
features_lr_list = [
    ['Parotid_meandose', 'OralCavity_Ext_meandose', 'Age'], # Taste
]
#lr_coefficients_list = [None, None, None, None, None]