model_name = "resnet_lrelu"

# model parameters

seg_target_labels = [0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0]
features_dl = [
               'Xerostomia_W01_Helemaal_niet', 'Xerostomia_W01_Een_beetje', 'Xerostomia_W01_Nogal_Heel_erg',
                'Dysphagia_W01_Grade0_1', 'Dysphagia_W01_Grade2', 'Dysphagia_W01_Grade3_4',
                'Smoking_1',
                'Loctum2_Larynx','Loctum2_Oral_Cavity','Loctum2_Overig','Loctum2_Pharynx',
                'T0','T1','T2','T3','T4','Tx',
                'N0','N1','N2','N3',
                'P16_Negatief','P16_Niet_bepaald','P16_Positief','WHO_0','WHO_1','WHO_2','WHO_3','WHO_4',
                ]
endpoint_list = ["Dysphagia_M06"]




resnet_model_depth = 10
n_input_channels = 3 
conv_block_layers = 1 
filters = [8, 8, 16, 32]
kernel_sizes = [7, 5, 4, 3]
strides = [[2,2,2], [2,2,2], [2,2,2], [2,2,2]]  
resnet_shortcut = 'B' 
conv1_t_size = 7
conv1_t_stride = 2
normalization = "NONE"
pad_value = 0  # (Padding) Value used for padding.
lrelu_alpha = 0.1  # (LeakyReLU) Negative slope.
pooling_conv_filters = "NONE"  
perform_pooling = false
pooling = "NONE" 
pooling_size = 2 
# linear layers
clinical_variables_position = 1
clinical_variables_linear_units =  [64, 8] 
linear_units = [16] 
dropout_p = 0.1
linear_units_endpoint = []
use_bias = true



# training parameters
weight_init_name = 'kaiming_uniform' 
kaiming_mode = 'fan_in' 
kaiming_nonlinearity = 'leaky_relu' 
gain = 0
optimizer_name = 'madgrad'
momentum = 0.85
weight_decay = 0
hessian_power = 1.0
use_lookahead = false
lookahead_k = 5
lookahead_alpha = 0.5 

loss_function_name = 'bce'
# loss_function_name = 'cross_entropy'  
# num_ohe_classes = 2  
label_weights = false 
label_pos_weights = false 

auxiliary_loss_func_name = "NONE" ## "SB-ECE" | "ESD" | None
SB_ECE_n_bins = 15
SB_ECE_temperature = 0.005
loss_reduction = 'none' # Daniel: do not change this
label_smoothing = 0  
scheduler_name = 'cosine' # [None, 'cosine', 'cyclic', 'exponential']. 
grad_max_norm = 1 
lr = 0.0001
T_0restart = 40 
T_mult = 1 
eta_min = 1e-10 

batch_size = 4

# augmentation parameters

perform_data_aug = true
data_aug_p = 0.3
data_aug_strength = 0.6
# AugMix
perform_augmix = false
mixture_width = 3  
mixture_depth = [1, 3] 
augmix_strength = 3
# MixUp
perform_mixup = true
mixup_alpha = 1.5





submodels_features_list = [
    [
        ['OralCavity_Ext_meandose', 'PCM_Med_meandose', 'PCM_Inf_meandose', 'Dysphagia_W01_Grade2', 'Dysphagia_W01_Grade3_4', 'Loctum2_Pharynx', 'Loctum2_Larynx'],  # Dysphagia submodel 1
        ['PCM_Sup_meandose', 'PCM_Med_meandose', 'PCM_Inf_meandose', 'Dysphagia_W01_Grade2', 'Dysphagia_W01_Grade3_4', 'Loctum2_Pharynx', 'Loctum2_Larynx']          # Dysphagia submodel 2
    ]]
features_lr_list = [
    ['OralCavity_Ext_meandose', 'PCM_Sup_meandose', 'PCM_Med_meandose', 'PCM_Inf_meandose', 'Dysphagia_W01_Grade2', 'Dysphagia_W01_Grade3_4', 'Loctum2_Pharynx', 'Loctum2_Larynx'], # Dysphagia
]
#lr_coefficients_list = ["NONE"]