general:
  region: 'LUNG'
  seed: 42
  device: "cuda"
  firstRun: false
  experiment_name: 'DETOX2-Lung_OS'
  trialNumber: "Trial_?"
  patientGroup: 0
  optimize: "loss"
  resultsCurrentDirectory: ""
  error_ignore: true
  endpointRatios: []
  testMode: False
  classImbalance: 0.25

columns:
  label: ["OS_Days","OS_Dead"]
  clinical_features: ["SmokerActive","SmokerStopped", "Gender",
  "Age","ChemoRad", "ImmunoTherapy",
  "OperationPerformed","SmokingUntilRecently","Pulmonary_Comorbidity", "RT_FractionDose"] #, "T_Stage","N_Stage","M_Stage"]
  logistic_regression_features: ['']

paths:
  csv: "C:/Users/r.van.der.wal/Documents/Data/2024_09_04/ClinicalData/2024_11_01/"
  images: "C:/Users/r.van.der.wal/Documents/Data/2024_09_04/ImageData/"
  output: "C:/Users/r.van.der.wal/Documents/Detox_lung/Results_OS/"
  results: "C:/Users/r.van.der.wal/Documents/Detox_lung/Results_OS/"

run:
  patienceExhausted: False
  patienceExhaustedIndex: 0

model:
  model_name: "resnet" #"dcnn_pooling"

  resnet:
    model_depth: 10    # [10, 18, 34, 50, 101, 152, 200]
    conv1_kernel_size: 7
    conv1_stride: 2
  densenet: 
    model_depth: 121  # [121, 169, 201, 264]
  ViT:
    vit_patch_size: 8
    vit_dim: 128
    vit_depth: 4
    vit_heads: 8
    vit_mlp_dim: 128
    vit_dim_head: 128
    vit_emb_dropout: 0.2
    vit_dropout_p: 0.2  
  TransRP:
    image_encoder: 'densenet'  # ['resnet', 'densenet'] (requires their respective configs)
    clinical_features_method: 'm2'  # ["m1", "m2", "m3", "m4", "m5"] 
    vit_patch_size: [1,1,1]
    vit_dim: 768
    vit_depth: 12
    vit_heads: 12
    vit_mlp_dim: 3072
    vit_dropout_p: 0.2  

  num_classes: 1
  n_down_blocks: 5
  filters: [8, 8, 16, 16, 32]
  kernel_sizes: [7, 5, 4, 3, 3]
  strides: [[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
  pad_value: 0
  lrelu_alpha: 0.1
  dropout_p: 0.06087816611628816
  perform_pooling: False
  n_linear_down_blocks: 1
  linear_units: [16]
  n_clinical_down_blocks: 2
  clinical_variables_position: 1
  clinical_variables_linear_units: [32,16]
  clinical_variables_dropout_p: [0.3581947628028867]
  use_bias: True
  pooling: 'max'    # avg, max, nan
  pooling_size: 2
  normalization: 'batch'
  conv_block_layers: 1
  num_ohe_classes: 1
  linear_units_endpoint: [64]

data:
  trainfile: 'stratified_sampling_full_manual_94_edited.csv'
  valfile: 'stratified_sampling_full_manual_94_edited.csv'
  splitvar: "Split"
  patientVar: 'PatientID'
  stratifyList: ["RP_OneYear", "ImmunoTherapy"]
  ExcludedVar: [] # "MissingLung"
  ExcludedValue: []
  imageKeys: ["ct","rtdose","segmentation_map"]


  dataloader:
    num_workers: 4           # number of workers (cores) to use for data loading in each training batch
    persistent_workers: true # recommend keep this as `true' for faster data loading

  preprocessing:
    isEnabled: false
    crop: false
    crop_shape: [96, 96, 96]
    ct:
      a_min: -1200
      a_max: 400
      b_min: 0
      b_max: 1
      clip: true
    rtdose:
      a_min: 0
      a_max: 8000
      b_min: 0
      b_max: 1
      clip: true
    segmentation_map:
      target_labels: []

  kFolds:
    isEnabled: true
    skip_badtrial: false
    Iterations: 4
    Splits: 4

  equalizer:
    isEnabled: True
    ratio: 0.5
    resamplingDirection: 'up'

  augmentation:
    isEnabled: true
    #augmentation_list: ['flip','affine','rotate']
    #prob: 0.9628202570846732
    #strength: 3.005578369584509

    list:
      flip:
        Isenabled: True
        prob: 0.5
      affine:
        Isenabled: True
        prob: 0.97
        translate_max: 14   # pixels
        scale_max: 0.02
        z_scale: -0.2
      rotate:
        Isenabled: True
        prob: 0.97
        max: 150 # degree
      noise:
        Isenabled: True
        prob: 0.3
        mean: 0
        std: 0.1

training:
  max_epochs: 60
  batch_size: 16
  validation_interval: 1
  patience: 20

  optimizer:
    name: "Adam"
    learning_rate: 0.00040096753586928423
    weight_decay: 0.0000001178312895422

  loss:
    name: 'NLLL'
    weight: [1.2]
    reduction: "none"
    strength_enabled: false
    lamb: 1.5
    margin: 1.0
    gamma: 2.0
    compensate_imbalance: True

  scheduler:
    name: "cosine"
    T_0: 40
    T_mult: 1
    eta_min: 0.00000001

  validation:
    num_auc_batches: 1

visualization:
  calibration:
    num_bins: 10
  confusion_matrix:
    threshold: 'YoudenJ'

hyperparam_tuning:
  WandB:
    IsEnabled: True
    API_Key: "7ed1cc01e74dab3990ca774ff0461cdcd3ea5c1c"
    MetricsMonitor: [ "train_AUC","train_loss","train_acc",
      "eval_AUC","eval_loss","eval_acc"]
  optuna:
    IsEnabled: True
    n_trials: 40
  # ----  Custom Params -------
  # Location:= path variabele in config
  hyperparams:
    Model_Selected:
      name: 'Model_Selected'
      type: 'categorical'
      location: ["model",'model_name']
      options: ['resnet']
    #Model_Depth:
    #  name: "Model_Depth"
    #  location: ["model","resnet","model_depth"]
    #  type: 'categorical'
    #  options: [10,18,34]
    Resampling_ratio:
      name: 'Resampling_ratio'
      type: 'float'
      location: ["data","equalizer","ratio"]  
      min: 0.5
      max: 0.5
    Clin_DropOut:
      name: 'Clin_Dropout'
      type: 'float'
      location: ["model","clinical_variables_dropout_p"]  
      min: 0.15
      max: 0.35
    Weight_decay: 
      name: 'Weight_Decay'
      type: 'float'
      location: ["training",'optimizer','weight_decay']
      min: 0.00000001
      max: 0.000001
    learning_rate: 
      name: 'Learning_rate'
      type: 'float'
      location: ['training','optimizer','learning_rate']
      min: 0.00005
      max: 0.003
    optimizer:
      name: "Optimizer" 
      type: 'categorical'
      location: ["training",'optimizer','name']
      options: ['Adam']
    loss_function:
      name: loss_function
      type: 'categorical'
      location: ['training','loss','name']
      options: ['NLLL']
    
    loss_lamb:
      name: Loss_Lamb
      type: 'float'
      location: ['training','loss','lamb']
      min: 0.1
      max: 3.0
    loss_margin:
      name: Loss_Margin
      type: 'float'
      location: ['training','loss','margin']
      min: 0.1
      max: 3.0
    loss_gamma:
      name: loss_gamma
      type: 'float'
      location: ['training','loss','gamma']
      min: 0.1
      max: 3.0
    
    batch_size:
      name: batch_size
      type: 'categorical'
      location: ["training","batch_size"]
      options: [16]

    augmentation_noise_std:
      name: augmentation_strength
      type: 'float'
      location: ['data','augmentation',"list","noise","std"]
      min: 0
      max: 0.6

    #augmentation_strength:
    #  name: augmentation_strength
    #  type: 'float'
    #  location: ['data','augmentation',"strength"]
    #  min: 2.5
    #  max: 5

    #augmentation_probability:
    #  name: augmentation_probability
    #  type: 'float'
    #  location: ['data','augmentation',"prob"]
    #  min: 0.96
    #  max: 0.96


    # ----  NN Layer Params -------
    # Indicate amount of layers for different parts of Neural Network
    #n_down_blocks:
    # type: 'int'
    # name: 'n_down_blocks'
    # location: ['model','n_down_blocks']
    # min: 2
    # max: 5
    # step: 1
    # log: False

    # n_linear_down_blocks:
    #  type: 'int'
    #  name: 'n_linear_down_blocks'
    #  location: ['model','n_linear_down_blocks']
    #  min: 1
    #  max: 2
    #  step: 1
    #  log: False

    #n_clinical_down_blocks:
    #  type: 'int'
    #  name: 'n_clinical_down_blocks'
    #  location: ['model','n_clinical_down_blocks']
    #  min: 0
    #  max: 3
    #  step: 1
    #  log: False
  
  # Complex hyperparams: Initialise every layer of the Neural Network with given ranges
  derived:
    n_down_blocks:
      filters:
        type: 'int'
        name: 'CNN_filter'
        location: ['model','filters']
        min: 8
        max: 32 # 64
        step: 8
        log: False
      kernel_sizes:
        type: 'int'
        name: 'CNN_kernel_size'
        location: ['model','kernel_sizes']
        min: 3
        max: 7
        step: 2
        log: False
      #strides:      
      #  type: 'categorical'
      #  name: 'stride'
      #  location: ['model','strides']
      #  options: [[2,2,2]]
    
    n_linear_down_blocks:
      filters:
        type: 'int'
        name: 'Linear_filter'
        location: ['model','linear_units']
        min: 8
        max: 32
        step: 8
        log: False

    n_clinical_down_blocks:
      filters:
        type: 'int'
        name: 'Clin_filter'
        location: ['model','clinical_variables_linear_units']
        min: 8
        max: 32
        step: 8
        log: False
      clin_pos:
        type: 'int'
        name: 'clin_pos'
        location: ['model','clinical_variables_position']
        min: 0
        max: 3
        step: 1
        log: False
      
        
Save:
  config: True
  output_values: True
  best_model: False
  fileNames:
    modelSummary: "modelSummary"
      