general:
  region: "HNC"
  seed: 42
  firstRun: false
  experiment_name: 'Xerostomia_M06'
  trialNumber: "test_run"
  resultsCurrentDirectory:  ""  # "C:/Users/d.c.macrae/Documents/pred_RT"
  testMode: False
  use_test_set: false

columns: # 
  labels:  ["OS"]
  labels_types: ['Event']
  clinical_features: [] # "Xerostomia_W01_Helemaal_niet", "Xerostomia_W01_Een_beetje", "Xerostomia_W01_Nogal_Heel_erg", "Geslacht", "Leeftijd"]
paths:
  csv: /home/macraedc/data/
  images: /home/macraedc/data/preprocessed_OS_dataset_2mm
  results: /home/macraedc/rt_pred_results

  # csv: "/scratch/p306883/DL_NTCP_Multitox/datasets/MT_dataset"
  # images: "/scratch/p306883/DL_NTCP_Multitox/datasets/MT_dataset/patients_high_res"  # patients_high_res
  # results: "/scratch/p306883/rt_pred_results"

  # csv: "C:/Users/d.c.macrae/Documents/datasets/MT_dataset"
  # images: "C:/Users/d.c.macrae/Documents/datasets/MT_dataset/patients"  # patients_high_res
  # results: "C:/Users/d.c.macrae/Documents/datasets/rt_pred_results"



model:
  model_name: "resnet"
  output_head:
    name: "multilabel"
    n_linear_layers: 1
    linear_units: [32] # shared layers for model head
    n_clinical_layers: 0
    clinical_variables_linear_units: []
    clinical_variables_position: 1
    n_linear_layers_endpoint: 0
    linear_units_endpoint: []
    num_ohe_classes: 1
  resnet:
    model_depth: 18    # [10, 18, 34, 50, 101, 152, 200]
    conv1_kernel_size: 5
    conv1_stride: 2
  
  
  # general model params
  lrelu_alpha: 0.1
  dropout_p: 0.1
  use_bias: True
  # Linear layer params (output head)
  

data:
  source: 'UMCG'  # ['UMCG', 'MDACC']
  dataset_csv: 'OPC_data.csv'  #
  stratify_on: ["Geslacht" ] # "Loctum2"
  image_keys:  ['ct', 'pet'] # , 'rtdose', 'segmentation_map']  # the keys of the images to load
  image_num_dimensions: 3
  event_endpoint_time_unit: "months"

  dataloader:
    num_workers: 4           # number of workers (cores) to use for data loading in each training batch
  
  preprocessing:
    isEnabled: true
    crop: true
    crop_shape: [96, 96, 96] # 192, 192] #  #  #  
    ct:
      a_min: -200
      a_max: 400
      b_min: 0
      b_max: 1
      clip: true
    rtdose:
      a_min: 0
      a_max: 8000
      b_min: 0
      b_max: 1
      clip: true
    segmentation_map:
      target_labels: [0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.1, 0.1, 0.0, 0.0, 0.0, 0.0]

  kFolds:
    n_iterations: 5
    n_splits: 5
    split_strategy: 'stratified'  # ['stratified', 'random']

  equalizer:
    isEnabled: false
    ratio: 0.5
    resamplingDirection: 'up'

  augmentation:
    isEnabled: true
    prob: 0.5   # probability of applying each augmentation (flip is always 0.5)
    list:
      flip:
        isEnabled: True
      random_crop:    # uses the crop_shape defined in preprocessing
        isEnabled: True
      affine:
        isEnabled: True
        translate_max: 6   # pixels
        scale_max: 0.02
        z_scale: -0.2
      rotate:
        isEnabled: True
        max: 15 # degree
      noise:
        isEnabled: False
        mean: 0
        std: 0.05
    
    mixup:
      isEnabled: false
      alpha: 2.0

training:
  max_epochs: 100
  batch_size: 8
  validation_interval: 1
  stopping_criteria: "loss"   # ['loss', 'metric']    # which criteria to use for early stopping
  patience: 10                                        # early stopping patience
  show_progress_bar: False

  optimizer:
    name: "Adam" # "SGD"
    learning_rate: 0.001
    weight_decay: 0.00
    momentum: 0.00 # 9   # for SGD
  
  loss:
    name: "focal"
    reduction: "none"
    BCE:
      pos_weight: [1]  # either a list, or a single value for all labels, or "auto" to calculate automatically

  scheduler:
    name: False # "cosine"

  GradNorm:                  
    isEnabled: False         # whether to use GradNorm to balance the gradients of the labels' losses
    alpha: 0.5               # alpha value for GradNorm (higher -> more imbalance. 0=equal. recommended: less than 2)
    learning_rate: 0.001     # learning rate for the GradNorm optimiser

evaluation:
  main_metric: 
    Binary: "AUC"    # the metric shown during training
    Event: "C-index"
  metrics_list: ["AUC", "accuracy", "F1_score", "ECE", "ACE"]
  metrics:
    threshold: 'YoudenJ'
    calibration_bins: 10
  visualisations: 
    list: ['calibration', 'reliability']
    n_bins: 10


hyperparam_tuning:
  WandB:
    isEnabled: false
    API_Key: "c7f0f65fac8b7178ad7c5859ba6114775b16e694"
    #MetricsMonitor: [ "train_AUC","train_loss","train_acc",
    #  "eval_AUC","eval_loss","eval_acc"]
  optuna:
    isEnabled: true
    objectives: ['val_mean_Event_C-index']          
    objective_direction: ["maximize"] #, "maximize"]
    n_trials: 200
    n_startup_trials: 30               # number of random trials to perform at the start of the optuna experiment
    kill_trial_threshold: 0.6     
  # ----  Custom Params -------
  # Location:= path variable in config
  hyperparams:
    learning_rate: 
      name: 'Learning_rate'
      type: 'float'
      location: ['training','optimizer','learning_rate']
      min: 0.00001
      max: 0.001
    optimizer:
      name: "Optimizer" 
      type: 'categorical'
      location: ["training",'optimizer','name']
      options: ['AdaBound','Adam','SGD']
    # MODEL
    model_depth:
      name: "ResNet_depth"
      type: 'categorical'
      location: ["model",'resnet','model_depth']
      options: [10, 18, 34]
    # loss_function:
    #   name: "Loss_function"
    #   type: 'categorical'
    #   location: ["training",'loss','name']
    #   options: ['BCE', 'focal']
    
    

saving:
  config: True
  best_model: True
  plot_training_slices:
    isEnabled: True
    folder_name: 'figures'
    every_n_epochs: 1
    n_patients_per_epoch: 1
    n_slices_per_patient: 8


