general:
  region: "HNC"
  seed: 42
  firstRun: false
  experiment_name: 'CV_layers_test'
  trialNumber: "1"
  resultsCurrentDirectory:  ""  # "C:/Users/d.c.macrae/Documents/pred_RT"
  testMode: false
  use_test_set: false

columns: # 
  labels:  ["Aspiration_M06", "Dysphagia_M06", "Sticky_M06", "Taste_M06", "Xerostomia_M06" ]
  clinical_features: ['Sex', 'Age',
                      'Aspiration_W01_Helemaal_niet','Aspiration_W01_Een_beetje',  'Aspiration_W01_Nogal_Heel_erg', 
                      'Dysphagia_W01_Grade0_1', 'Dysphagia_W01_Grade2', 'Dysphagia_W01_Grade3_4', 
                      'Sticky_W01_Helemaal_niet', 'Sticky_W01_Een_beetje', 'Sticky_W01_Nogal_Heel_erg',
                      'Taste_W01_Helemaal_niet','Taste_W01_Een_beetje',  'Taste_W01_Nogal_Heel_erg', 
                      'Xerostomia_W01_Helemaal_niet', 'Xerostomia_W01_Een_beetje', 'Xerostomia_W01_Nogal_Heel_erg',
                      #'Loctum2_Larynx', 'Loctum2_Oral_Cavity', 'Loctum2_Overig', 'Loctum2_Pharynx',] # ["Xerostomia_W01_Helemaal_niet", "Xerostomia_W01_Een_beetje", "Xerostomia_W01_Nogal_Heel_erg", "Sex", "Age"]
                      ]
paths:
  csv: "C:/Users/S.P.M. de Vette/OneDrive - UMCG/Documents/DL_NTCP_Multitox/datasets/MT_dataset" # "C:/Users/d.c.macrae/Documents/datasets/MT_dataset"
  images: "C:/Users/S.P.M. de Vette/OneDrive - UMCG/Documents/DL_NTCP_Multitox/datasets/MT_dataset/patients" # patients_high_res/"  # "C:/Users/d.c.macrae/Documents/datasets/MT_dataset/patients/"
  
  #csv: "C:/Users/S.P.M. de Vette/OneDrive - UMCG/Documents/DL_NTCP_Multitox/datasets/MDACC_dataset" # "C:/Users/d.c.macrae/Documents/datasets/MT_dataset"
  #images: "C:/Users/S.P.M. de Vette/OneDrive - UMCG/Documents/DL_NTCP_Multitox/datasets/MDACC_dataset/patients" # patients_high_res/"  # "C:/Users/d.c.macrae/Documents/datasets/MT_dataset/patients/"
  
  results: "C:/Users/S.P.M. de Vette/OneDrive - UMCG/Desktop/pred_RT_results" # "C:/Users/d.c.macrae/Documents/pred_rt_results"

  # csv: "/scratch/p306883/DL_NTCP_Multitox/datasets/MT_dataset"
  # images: "/scratch/p306883/DL_NTCP_Multitox/datasets/MT_dataset/patients_high_res"  # patients_high_res
  # results: "/scratch/p306883/rt_pred_results"

  # csv: "C:/Users/d.c.macrae/Documents/datasets/MT_dataset"
  # images: "C:/Users/d.c.macrae/Documents/datasets/MT_dataset/patients"  # patients_high_res
  # results: "C:/Users/d.c.macrae/Documents/datasets/rt_pred_results"



model:
  model_name: "resnet"
  output_head:
    name: "multitox"
  resnet:
    model_depth: 10    # [10, 18, 34, 50, 101, 152, 200]
    conv1_kernel_size: 5
    conv1_stride: 2
  densenet: 
    model_depth: 121  # [121, 169, 201, 264]
  ViT:
    vit_patch_size: 8
    vit_dim: 128
    vit_depth: 4
    vit_heads: 8
    vit_mlp_dim: 128
    vit_dim_head: 128
    vit_emb_dropout: 0.2
    vit_dropout_p: 0.2  
  TransRP:
    image_encoder: 'resnet'  # ['resnet', 'densenet'] (requires their respective configs)
    clinical_features_method: 'cls' # 'm2'  # ["m1", "m2", "m3", "mcb", 'cls', ''m2_v2] 
    vit_patch_size: [1,1,1]
    vit_dim: 256   # 256, 512, 768
    vit_depth: 4    # 4, 6, 8
    vit_heads: 32   # 12, 16, 32, 64, 128
    vit_mlp_dim: 512  # 256, 512, 1024
    vit_dropout_p: 0.2    # 0, 0.1, 0.2
  
  # general model params
  lrelu_alpha: 0.1
  dropout_p: 0.1
  use_bias: True
  # Linear layer params (output head)
  n_linear_layers: 0
  linear_units: [256] # shared layers for model head
  n_clinical_layers: 0
  clinical_variables_linear_units: []
  clinical_variables_position: 1
  n_linear_layers_endpoint: 1
  linear_units_endpoint: [64]
  num_ohe_classes: 1

data:
  source: 'UMCG'  # ['UMCG', 'MDACC']
  dataset_csv: 'stratified_sampling_test_542.csv'  #  MDACC_features_present
  stratify_on: ["Aspiration_M06", "Dysphagia_M06", "Sticky_M06", "Taste_M06", "Xerostomia_M06" ] # "Loctum2"
  image_keys:  ['ct', 'rtdose', 'segmentation_map']  # the keys of the images to load
  image_num_dimensions: 3

  dataloader:
    num_workers: 8           # number of workers (cores) to use for data loading in each training batch
  
  preprocessing:
    isEnabled: true
    crop: true
    crop_shape: [96, 96, 96] # 192, 192] #  #  #  
    ct:
      a_min: -200
      a_max: 400
      b_min: 0
      b_max: 1
      clip: true
    rtdose:
      a_min: 0
      a_max: 8000
      b_min: 0
      b_max: 1
      clip: true
    segmentation_map:
      target_labels: [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

  kFolds:
    n_iterations: 1
    n_splits: 5
    split_strategy: 'stratified'  # ['stratified', 'random']

  equalizer:
    isEnabled: false
    ratio: 0.5
    resamplingDirection: 'up'

  augmentation:
    isEnabled: true
    prob: 0.5   # probability of applying each augmentation (flip is always 0.5)
    list:
      flip:
        isEnabled: True
      random_crop:    # uses the crop_shape defined in preprocessing
        isEnabled: True
      affine:
        isEnabled: True
        translate_max: 6   # pixels
        scale_max: 0.02
        z_scale: -0.2
      rotate:
        isEnabled: True
        max: 15 # degree
      noise:
        isEnabled: False
        mean: 0
        std: 0.05
    
    mixup:
      isEnabled: false
      alpha: 2.0

training:
  max_epochs: 1
  batch_size: 16
  validation_interval: 1
  stopping_criteria: "loss"   # ['loss', 'metric']    # which criteria to use for early stopping
  patience: 30                                        # early stopping patience
  show_progress_bar: False

  optimizer:
    name: "SGD" # "SGD"
    learning_rate: 0.001
    weight_decay: 0.00
    momentum: 0.00 # 9   # for SGD
  
  loss:
    name: "BCE"
    reduction: "none"
    BCE:
      pos_weight: [1, 1, 1, 1, 1]  # either a list, or a single value for all labels, or "auto" to calculate automatically

  scheduler:
    name: False # "cosine"
    T_0: 40
    T_mult: 1
    eta_min: 0.00000001

  GradNorm:                  
    isEnabled: True         # whether to use GradNorm to balance the gradients of the labels' losses
    alpha: 0.5               # alpha value for GradNorm (higher -> more imbalance. 0=equal. recommended: less than 2)
    learning_rate: 0.001     # learning rate for the GradNorm optimiser

evaluation:
  main_metric: "AUC"
  metrics_list: ["AUC", "accuracy", "F1_score", "ECE", "ACE"]
  metrics:
    threshold: 'YoudenJ'
    calibration_bins: 10
  visualisations: 
    list: ['calibration', 'reliability']
    n_bins: 10


hyperparam_tuning:
  WandB:
    isEnabled: true
    API_Key: "c7f0f65fac8b7178ad7c5859ba6114775b16e694"
    #MetricsMonitor: [ "train_AUC","train_loss","train_acc",
    #  "eval_AUC","eval_loss","eval_acc"]
  optuna:
    isEnabled: true
    objectives: ["val_mean_AUC"]          
    objective_direction: ["maximize"]
    n_trials: 200
  # ----  Custom Params -------
  # Location:= path variable in config
  hyperparams:
    n_clinical_layers:
      type: 'int'
      name: 'n_clinical_layers'
      location: ['model','n_clinical_layers']
      min: 0
      max: 2
      step: 1
      log: False
    n_linear_layers:
      type: 'int'
      name: 'n_linear_layers'
      location: ['model','n_linear_layers']
      min: 1
      max: 3
      step: 1
      log: False


  derived:
    n_linear_layers:
      linear_units:
        type: 'categorical'
        name: 'LL_shared_'
        location: ['model','linear_units']
        options: [64,128,256,512]
        log: False
      clinical_variables_position:
        type: 'int'
        name: 'clinical_variables_position'
        location: ['model','clinical_variables_position']
        min: 1
        max: 2
        step: 1
        log: False

    n_clinical_layers:
      clinical_variables_linear_units:
        type: 'categorical'
        name: 'CLC_shared_'
        location: ['model','clinical_variables_linear_units']
        options: [16,32,64]
        log: False
    
      #log: False
    # MODEL
    

saving:
  config: True
  best_model: True
  plot_training_slices:
    isEnabled: True
    folder_name: 'figures'
    every_n_epochs: 50
    n_patients_per_epoch: 1
    n_slices_per_patient: 8


