


data:
  n_patients_total: 400

training:
  max_epochs: 3
  batch_size: 8
  validation_interval: 1
  patience: 5

data:
  kFolds:
    isEnabled: true
    n_splits: 5        # the number of data splits to make
    n_iterations: 1    # the number of k-fold iterations to perform (i.e. how many to actually train, must be less than or equal to 'n_splits')