CITOR:
  dysphagia_early:
    label: Dysphagia_w06
    models:
      model1:
        features:
        - OralCavity_Ext_meandose
        - PCM_Med_meandose
        - PCM_Inf_meandose
        - DYSFAGIE_UMCGshort_W01_Grade2
        - DYSFAGIE_UMCGshort_W01_Grade3_4
        - Loctum_OC
        - Loctum_Pharynx
        - Loctum_Larynx
      model2:
        features:
        - PCM_Sup_meandose
        - PCM_Med_meandose
        - PCM_Inf_meandose
        - DYSFAGIE_UMCGshort_W01_Grade2
        - DYSFAGIE_UMCGshort_W01_Grade3_4
        - Loctum_OC
        - Loctum_Pharynx
        - Loctum_Larynx
  dysphagia_late:
    label: Dysphagia_M06
    models:
      model1:
        features:
        - OralCavity_Ext_meandose
        - PCM_Med_meandose
        - PCM_Inf_meandose
        - Dysphagia_W01_Grade2
        - Dysphagia_W01_Grade3_4
        - Loctum2_Pharynx
        - Loctum2_Larynx
      model2:
        features:
        - PCM_Sup_meandose
        - PCM_Med_meandose
        - PCM_Inf_meandose
        - Dysphagia_W01_Grade2
        - Dysphagia_W01_Grade3_4
        - Loctum2_Pharynx
        - Loctum2_Larynx
  sticky_saliva_early:
    label: Sticky_saliva_w06
    models:
      model1:
        features:
        - Sticky_W01_Een_beetje
        - Sticky_W01_Heel_erg
        - Sticky_W01_Helemaal_niet
        - Submandibular_meandose
  sticky_saliva_late:
    label: Sticky_M06
    models:
      model1:
        features:
        - Sticky_W01_Een_beetje
        - Sticky_W01_Heel_erg
        - Submandibular_meandose
      model2:
        features:
        - Sticky_W01_Een_beetje
        - Sticky_W01_Heel_erg
        - Parotid_sum_sqrt
  taste_loss_early:
    label: Taste_loss_w06
    models:
      model1:
        features:
        - OralCavity_mean_ln
        - Age
  taste_loss_late:
    label: Taste_M06
    models:
      model1:
        features:
        - OralCavity_mean_sqrt
        - Age
      model2:
        features:
        - Parotid_mean_ln
        - Age
  xerostomia_early:
    label: Xerostomia_w06
    models:
      model1:
        features:
        - Submandibular_meandose
        - Xerostomia_W01_Een_beetje
        - Xerostomia_W01_Heel_erg
        - Xerostomia_W01_Helemaal_niet
      model2:
        features:
        - Parotid_sum_sqrt
        - Xerostomia_W01_Een_beetje
        - Xerostomia_W01_Heel_erg
        - Xerostomia_W01_Helemaal_niet
  xerostomia_late:
    label: Xerostomia_M06
    models:
      model1:
        features:
        - Submandibular_meandose
        - Xerostomia_W01_Een_beetje
        - Xerostomia_W01_Heel_erg
        - Xerostomia_W01_Helemaal_niet
      model2:
        features:
        - Parotid_sum_sqrt
        - Xerostomia_W01_Een_beetje
        - Xerostomia_W01_Heel_erg
        - Xerostomia_W01_Helemaal_niet
columns:
  clinical_features:
  - Sex
  - Age
  - Aspiration_W01_Helemaal_niet
  - Aspiration_W01_Een_beetje
  - Aspiration_W01_Nogal_Heel_erg
  - Dysphagia_W01_Grade0_1
  - Dysphagia_W01_Grade2
  - Dysphagia_W01_Grade3_4
  - Sticky_W01_Helemaal_niet
  - Sticky_W01_Een_beetje
  - Sticky_W01_Nogal_Heel_erg
  - Taste_W01_Helemaal_niet
  - Taste_W01_Een_beetje
  - Taste_W01_Nogal_Heel_erg
  - Xerostomia_W01_Helemaal_niet
  - Xerostomia_W01_Een_beetje
  - Xerostomia_W01_Nogal_Heel_erg
  labels:
  - Aspiration_M06
  - Dysphagia_M06
  - Sticky_M06
  - Taste_M06
  - Xerostomia_M06
data:
  augmentation:
    isEnabled: true
    list:
      affine:
        isEnabled: true
        scale_max: 0.02
        translate_max: 6
        z_scale: -0.2
      flip:
        isEnabled: true
      noise:
        isEnabled: true
        mean: 0
        std: 0.01
      random_crop:
        isEnabled: true
      rotate:
        isEnabled: true
        max: 15
    mixup:
      alpha: 1.7244367682922501
      isEnabled: true
    prob: 0.5
  dataloader:
    dataloader_type: standard
    dataset_type: cache
    num_workers: 8
    smartcache:
      cache_rate: 0.5
      num_replace_workers: 4
  dataset_csv: stratified_sampling_test_542.csv
  equalizer:
    isEnabled: false
    ratio: 0.5
    resamplingDirection: up
  excluded_values: []
  excluded_variable_name: []
  image_keys:
  - ct
  - rtdose
  - segmentation_map
  image_num_dimensions: 3
  kFolds:
    n_iterations: 5
    n_splits: 5
    split_strategy: stratified
    validation_size: 0.2
  preprocessing:
    crop: true
    crop_shape:
    - 96
    - 192
    - 192
    ct:
      a_max: 400
      a_min: -200
      b_max: 1
      b_min: 0
      clip: true
    isEnabled: true
    mri:
      a_max: 12345
      a_min: 0
      b_max: 1
      b_min: 0
    needs_label_mapping:
    - segmentation_map
    needs_scaling:
    - ct
    - rtdose
    - mri
    rtdose:
      a_max: 8000
      a_min: 0
      b_max: 1
      b_min: 0
      clip: true
    segmentation_map:
      target_labels:
      - 0.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
  source: UMCG
  stratify_on:
  - Aspiration_M06
  - Dysphagia_M06
  - Sticky_M06
  - Taste_M06
  - Xerostomia_M06
evaluation:
  main_metric: AUC
  metrics:
    calibration_bins: 10
    threshold: YoudenJ
  metrics_list:
  - AUC
  - accuracy
  - F1_score
  - ECE
  - ACE
  visualisations:
    list:
    - calibration
    - reliability
    n_bins: 10
general:
  experiment_name: HP_TRP_HigherRes2_BEST
  firstRun: false
  region: HNC
  resultsCurrentDirectory: /scratch/s3719332/rt_pred_results/HP_TRP_HigherRes2_BEST/Trial_32/KFold1
  seed: 42
  testMode: false
  trialNumber: Trial_32
  use_test_set: false
hyperparam_tuning:
  WandB:
    API_Key: c7f0f65fac8b7178ad7c5859ba6114775b16e694
    isEnabled: true
  derived:
    n_linear_layers:
      filters:
        location:
        - model
        - linear_units
        log: false
        name: LL_shared_
        options:
        - 64
        - 128
        - 256
        - 512
        type: categorical
    n_linear_layers_endpoint:
      filters:
        location:
        - model
        - linear_units_endpoint
        log: false
        name: LL_endpoint_
        options:
        - 16
        - 32
        - 64
        type: categorical
  hyperparams:
    LRELU_alpha:
      location:
      - model
      - lrelu_alpha
      max: 0.1
      min: 0
      name: LRELU_alpha
      type: float
    clinical_features_method:
      location:
      - model
      - TransRP
      - clinical_features_method
      name: clinical_features_method
      options:
      - m1
      - m2
      type: categorical
    dropout_p:
      location:
      - model
      - dropout_p
      max: 0.3
      min: 0
      name: dropout_p
      type: float
    learning_rate:
      location:
      - training
      - optimizer
      - learning_rate
      name: learning_rate
      options:
      - 0.01
      - 0.001
      - 0.0001
      type: categorical
    mixup_alpha:
      location:
      - data
      - augmentation
      - mixup
      - alpha
      max: 5
      min: 0
      name: mixup_alpha
      type: float
    n_linear_layers:
      location:
      - model
      - n_linear_layers
      log: false
      max: 3
      min: 1
      name: n_linear_layers
      step: 1
      type: int
    n_linear_layers_endpoint:
      location:
      - model
      - n_linear_layers_endpoint
      log: false
      max: 3
      min: 1
      name: n_linear_layers_endpoint
      step: 1
      type: int
    noise:
      location:
      - data
      - augmentation
      - list
      - noise
      - isEnabled
      name: noise
      options:
      - true
      - false
      type: categorical
    vit_depth:
      location:
      - model
      - TransRP
      - vit_depth
      name: vit_depth
      options:
      - 4
      - 6
      - 8
      type: categorical
    vit_dim:
      location:
      - model
      - TransRP
      - vit_dim
      name: vit_dim
      options:
      - 256
      - 512
      - 768
      type: categorical
    vit_dropout_p:
      location:
      - model
      - TransRP
      - vit_dropout_p
      name: vit_dropout_p
      options:
      - 0
      - 0.1
      - 0.2
      type: categorical
    vit_heads:
      location:
      - model
      - TransRP
      - vit_heads
      name: vit_heads
      options:
      - 16
      - 32
      - 64
      - 128
      type: categorical
    vit_mlp_dim:
      location:
      - model
      - TransRP
      - vit_mlp_dim
      name: vit_mlp_dim
      options:
      - 256
      - 512
      - 1024
      type: categorical
  optuna:
    isEnabled: false
    kill_trial_threshold: 0.6
    n_trials: 200
    objective_direction:
    - maximize
    objectives:
    - val_mean_AUC
model:
  TransRP:
    clinical_features_method: m2
    image_encoder: densenet
    vit_depth: 4
    vit_dim: 256
    vit_dropout_p: 0
    vit_heads: 64
    vit_mlp_dim: 1024
    vit_patch_size:
    - 1
    - 1
    - 1
  ViT:
    vit_depth: 4
    vit_dim: 128
    vit_dim_head: 128
    vit_dropout_p: 0.2
    vit_emb_dropout: 0.2
    vit_heads: 8
    vit_mlp_dim: 128
    vit_patch_size: 8
  clinical_variables_linear_units: []
  clinical_variables_position: 1
  cnn_pooling:
    conv_block_layers: 1
    filters:
    - 8
    - 8
    - 16
    - 16
    - 32
    kernel_sizes:
    - 7
    - 5
    - 4
    - 3
    - 3
    normalization: batch
    pad_value: 0
    pooling: max
    pooling_size: 2
    strides:
    - - 1
      - 1
      - 1
    - - 1
      - 1
      - 1
    - - 1
      - 1
      - 1
    - - 1
      - 1
      - 1
    - - 1
      - 1
      - 1
  densenet:
    model_depth: 121
  dropout_p: 0.02595495832717444
  efficientnetv2:
    use_bias: true
  linear_units:
  - 256
  linear_units_endpoint:
  - 16
  - 32
  lrelu_alpha: 0.0731576958075853
  model_name: TransRP
  n_clinical_layers: 0
  n_linear_layers: 2
  n_linear_layers_endpoint: 2
  num_ohe_classes: 1
  output_head:
    name: multitox
  resnet:
    conv1_kernel_size: 5
    conv1_stride: 2
    model_depth: 10
  use_bias: true
paths:
  csv: /scratch/p306883/DL_NTCP_Multitox/datasets/MT_dataset
  images: /scratch/p306883/DL_NTCP_Multitox/datasets/MT_dataset/patients_high_res
  results: /scratch/p306883/rt_pred_results
saving:
  best_model: true
  config: true
  filenames:
    config_yaml: DlModel_Config.yaml
    ensemble_predictions_csv: ensemble_predictions.csv
    model_summary: model_summary.txt
    model_weights: DlModel_Weights.pth
    predictions_csv: model_predictions.csv
    test_set_predictions_csv: test_set_predictions.csv
  plot_training_slices:
    every_n_epochs: 50
    folder_name: figures
    isEnabled: true
    n_patients_per_epoch: 1
    n_slices_per_patient: 8
training:
  GradNorm:
    alpha: 0.5
    isEnabled: false
    learning_rate: 0.001
  batch_size: 8
  loss:
    ASL:
      gamma_neg: 4
      gamma_pos: 1
    BCE:
      pos_weight:
      - 1
    focal:
      alpha: 0.25
      gamma: 2
    name: BCE
    reduction: none
  max_epochs: 200
  optimizer:
    learning_rate: 0.0001
    momentum: 0.8
    name: Adam
    weight_decay: 0.0
  patience: 20
  scheduler:
    T_0: 40
    T_mult: 1
    eta_min: 1.0e-08
    name: false
  show_progress_bar: false
  stopping_criteria: loss
  validation_interval: 1




CITOR:  # features of the CITOR (sub-)models for the early and late endpoints
  dysphagia_late:
    label: "Dysphagia_M06"
    models:
      model1:
        features: ['OralCavity_Ext_meandose','PCM_Med_meandose','PCM_Inf_meandose','Dysphagia_W01_Grade2','Dysphagia_W01_Grade3_4','Loctum2_Pharynx','Loctum2_Larynx'] #,'Dysphagia_W01_Grade0_1' ,'Loctum2_Oral_Cavity'
      model2:
        features: ['PCM_Sup_meandose','PCM_Med_meandose','PCM_Inf_meandose','Dysphagia_W01_Grade2','Dysphagia_W01_Grade3_4','Loctum2_Pharynx','Loctum2_Larynx'] #,'Loctum2_Oral_Cavity','Dysphagia_W01_Grade0_1'
  dysphagia_early:
    label: "Dysphagia_w06"
    models:
      model1:
        features: ['OralCavity_Ext_meandose','PCM_Med_meandose','PCM_Inf_meandose','DYSFAGIE_UMCGshort_W01_Grade2', 'DYSFAGIE_UMCGshort_W01_Grade3_4','Loctum_OC','Loctum_Pharynx','Loctum_Larynx']
      model2:
        features: ['PCM_Sup_meandose', 'PCM_Med_meandose', 'PCM_Inf_meandose', 'DYSFAGIE_UMCGshort_W01_Grade2', 'DYSFAGIE_UMCGshort_W01_Grade3_4', 'Loctum_OC', 'Loctum_Pharynx', 'Loctum_Larynx'] 
  xerostomia_late:
    label: 'Xerostomia_M06'
    models:
      model1:
        features: ['Submandibular_meandose','Xerostomia_W01_Een_beetje','Xerostomia_W01_Nogal_Heel_erg','Xerostomia_W01_Helemaal_niet'] #,'Xerostomia_W01_Helemaal_niet'
      model2:
        features: ['Parotid_sum_of_sqrts','Xerostomia_W01_Een_beetje','Xerostomia_W01_Nogal_Heel_erg','Xerostomia_W01_Helemaal_niet'] # 'Xerostomia_W01_Helemaal_niet' 
  xerostomia_early:
    label: 'Xerostomia_w06'
    models:
      model1:
        features: ['Submandibular_meandose','Xerostomia_W01_Een_beetje','Xerostomia_W01_Nogal_Heel_erg','Xerostomia_W01_Helemaal_niet'] 
      model2:
        features: ['Parotid_sum_of_sqrts','Xerostomia_W01_Een_beetje','Xerostomia_W01_Nogal_Heel_erg','Xerostomia_W01_Helemaal_niet'] 
  taste_late:
    label: 'Taste_M06'
    models:
      model1: 
        features: ['Parotid_log_of_mean', 'Oral_Cavity_sqrt_of_mean','Leeftijd'] #  No submodels !
  taste_early:
    label: 'Taste_loss_w06'
    models:
      model1: 
        features: ['Oral_Cavity_log_of_mean','Leeftijd'] # ln(oral cavity), age
  sticky_saliva_late:
    label: 'Sticky_M06'
    models:
      model1:
        features: ['Submandibular_meandose', 'Sticky_W01_Een_beetje','Sticky_W01_Nogal_Heel_erg'] # ,'Sticky_W01_Helemaal_niet' BSL scores, submandibular
      model2:
        features: ['Parotid_sum_of_sqrts', 'Sticky_W01_Een_beetje','Sticky_W01_Nogal_Heel_erg'] # ,'Sticky_W01_Helemaal_niet' BSL, parotid (sqrt(mean dose parotid ipsi) + sqrt(mean dose parotid contra))
  sticky_saliva_early:
    label: 'Sticky_saliva_w06'
    models:
      model1: 
        features: ['Sticky_W01_Een_beetje','Sticky_W01_Nogal_Heel_erg','Submandibular_meandose'] # BSL, Submandibular glands # 'Sticky_W01_Helemaal_niet'