from ModelCard import ModelCard


import os
import sys
import subprocess
from pipreqs import pipreqs 
from pathlib import Path
path_Project = Path(os.getcwd()).parent
path_Git = path_Project

def IncludeDirectory(path, index = 0, indexStop = -1):
    if(os.path.exists(path) and (index <= indexStop or indexStop == -1)):
        sys.path.append(path)
        children = os.listdir(path)
        for i in range(len(children)):
            pathChild = os.path.join(path,children[i])
            if(os.path.isdir(pathChild)):
                IncludeDirectory(pathChild, index + 1, indexStop)

# Activate the function
IncludeDirectory(path_Git,0,1)

from src.config_presets.tools.get_config import get_config

config = get_config('Base_config')

path_libraryDepend = os.path.join(config["saving"]["ModelCard"]["saveLocation"],config["saving"]["filenames"]["library_dependencies_file"])

pathExport = r"C:\Users\WalR\OneDrive - UMCG\Documents\Modelcards\autogenerated_card.json"

path_libraryDepend = os.path.join(config["saving"]["ModelCard"]["saveLocation"],config["saving"]["filenames"]["library_dependencies_file"])
current_dir = os.path.dirname(os.path.abspath(__file__))

# Run pip freeze and write to file
with open(path_libraryDepend, "w") as f:
    subprocess.run([sys.executable, "-m", "pip", "freeze"], stdout=f, check=True)
# Set location where it is created
libraryRequirementList = os.path.basename(path_libraryDepend)



mCard = ModelCard()
# Cleaning the card
#mCard.clean()
# Absorb information
#print(mCard.data['card_metadata']['card_creation_date'])
mCard.absorb_config_details(config)
# Infuse additional info
mCard.setitem(["technical_specifications","hw_and_sw","libraries_and_dependencies"], libraryRequirementList)
# Write to location
mCard.to_json(pathExport)

